name: Deploying

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      
      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Medic loyihasi uchun serverda katalog mavjud yoki yo'qligini tekshirish
            if [ ! -d "Medicine_and_Health_Users" ]; then
              echo "Project not found. Cloning..."
              git clone git@github.com:Ozodbek2129/Medicine_and_Health_Users.git
              cd Medicine_and_Health_Users
              sudo docker compose up -d
            else
              echo "Project exists. Pulling latest changes..."
              cd Medicine_and_Health_Users
              git pull
              sudo docker compose down
              sudo docker compose up -d
            fi
